ktor:
    application:
        modules:
            - ApplicationKt.module
    deployment:
        port: 8080

database:
  url: jdbc:postgresql://localhost:5432/garage-manager-api
  username: postgres
  password: postgres
  driver: org.postgresql.Driver